### ISSUE TITLE
Allow synced zoom in any mode

### ISSUE THREAD

**Issue by bigConifer** [VincentEngel/VES-Image-Compare#10]
It would be great, if the sync zoom feature was available in all comparison modes. 

I think the best way to implement it would be a global link/unlink button in main activity (e.g. at the position marked in the screenshot). IMO there is no need for toggling synced zoom inside compare mode. So the control button in "side by side" mode could be removed again. 

![position](https://user-images.githubusercontent.com/64743731/198832885-9db236cd-e3df-4a7f-b677-0eb32e96a298.jpg)

**Comment by VincentEngel** [comment]
Hey @bigConifer ,

thanks for your suggestion. I will look into how to implement it.

Add synced zoom to:

- [ ] Slide
- [ ] Tap
- [ ] Transparent

**Comment by VincentEngel** [comment]
Added sync zoom in Tap and Transparent modes in latest release 2.0.5 https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.0.5

I personally don't want to leave a mode to change the synced zoom, so you can enable/disable it in each mode that supports it.

As for the Slide mode, I am not sure how it should work there. The zoom resets whenever you "cut" the front image, so synced zoom feels strange. Which is why I did not implement it. If you have an idea on how it should behave, feel free to create another issue 👍

**Comment by bigConifer** [comment]
Sorry for my delayed answer. Many thanks for implementing it!

> I personally don't want to leave a mode to change the synced zoom setting

Are there really use cases, where you switch back and forth synced zoom while comparing? 
I would actually say for each comparison there is only one suitable setting (synced or not synced) depending on the content of the images. So it's easy to decide before entering the compare mode...

> If you have an idea on how it should behave, feel free to create another issue 

OK thanks, I will take a look 👍
